{% set name = "SoFiA-2" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/SoFiA-Admin/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 90b3503d88138a285525dadf8ec0c29281c1ad008fcda51246d3e7c8782f02f3
    folder: sources
  - url: https://github.com/SoFiA-Admin/SoFiA-2/wiki/documents/sofia_test_datacube.tar.gz
    sha256: b4ec8fc0f8c6eb3b596d9845ddbaeb14635b8604cfa55e2c8b39eccb23b555f9
    folder: test-data

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - sed
  host:
    - wcslib
    - openmp
  run:
    - wcslib
    - _openmp_mutex

test:
  source_files:
    - test-data/
  commands:
    - cd test-data
    - sofia sofia.par

about:
  home: https://github.com/SoFiA-Admin/SoFiA-2
  license: GPL-3.0-only
  license_family: GPL
  license_file: sources/LICENSE
  summary: This is version 2 of the HI Source Finding Application (SoFiA)

extra:
  recipe-maintainers:
    - sebastian-luna-valero
